Traceback (most recent call last):
  File "/home/jlg/mvdoc/miniconda3/envs/voxelwise_tutorials/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/jlg/mvdoc/miniconda3/envs/voxelwise_tutorials/lib/python3.10/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/jlg/mvdoc/miniconda3/envs/voxelwise_tutorials/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
  File "/home/jlg/mvdoc/miniconda3/envs/voxelwise_tutorials/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/jlg/mvdoc/miniconda3/envs/voxelwise_tutorials/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/jlg/mvdoc/miniconda3/envs/voxelwise_tutorials/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/jlg/mvdoc/miniconda3/envs/voxelwise_tutorials/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
username = input("CRCNS username: ")
password = getpass.getpass("CRCNS password: ")

for datafile in DATAFILES:
    local_filename = download_crcns(datafile, username, password,
                                    destination=directory, unpack=True)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mStdinNotImplementedError[0m                  Traceback (most recent call last)
Cell [0;32mIn[3], line 1[0m
[0;32m----> 1[0m username [38;5;241m=[39m [38;5;28;43minput[39;49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mCRCNS username: [39;49m[38;5;124;43m"[39;49m[43m)[49m
[1;32m      2[0m password [38;5;241m=[39m getpass[38;5;241m.[39mgetpass([38;5;124m"[39m[38;5;124mCRCNS password: [39m[38;5;124m"[39m)
[1;32m      4[0m [38;5;28;01mfor[39;00m datafile [38;5;129;01min[39;00m DATAFILES:

File [0;32m~/miniconda3/envs/voxelwise_tutorials/lib/python3.10/site-packages/ipykernel/kernelbase.py:1269[0m, in [0;36mKernel.raw_input[0;34m(self, prompt)[0m
[1;32m   1267[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28mself[39m[38;5;241m.[39m_allow_stdin:
[1;32m   1268[0m     msg [38;5;241m=[39m [38;5;124m"[39m[38;5;124mraw_input was called, but this frontend does not support input requests.[39m[38;5;124m"[39m
[0;32m-> 1269[0m     [38;5;28;01mraise[39;00m StdinNotImplementedError(msg)
[1;32m   1270[0m [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_input_request(
[1;32m   1271[0m     [38;5;28mstr[39m(prompt),
[1;32m   1272[0m     [38;5;28mself[39m[38;5;241m.[39m_parent_ident[[38;5;124m"[39m[38;5;124mshell[39m[38;5;124m"[39m],
[1;32m   1273[0m     [38;5;28mself[39m[38;5;241m.[39mget_parent([38;5;124m"[39m[38;5;124mshell[39m[38;5;124m"[39m),
[1;32m   1274[0m     password[38;5;241m=[39m[38;5;28;01mFalse[39;00m,
[1;32m   1275[0m )

[0;31mStdinNotImplementedError[0m: raw_input was called, but this frontend does not support input requests.

